feat: add login page
TIHLDE/kontresv2 pull request #22
Opened 2024-01-29 15:34 UTC by ConradOsvik

login  page

- A form wrapped by a card component
- A server action triggered when the form is submitted
- A getUser util function, taking in parameters `user_id` and `password` returning the access token
- The page takes in the search param `redirect` which is where it should redirect if the user is logged in or logging in

2024-01-29 16:04 UTC, MindChirp requested changes

2024-01-29 16:04 UTC, frikkbol commented on src/app/login/actions.ts
> +    console.log(data)
Fjern plsssss

2024-01-29 16:04 UTC, frikkbol commented on src/app/login/actions.ts
> +    console.log(_redirect)
Fjern

2024-01-29 16:04 UTC, frikkbol commented on src/app/login/page.tsx
> +                <form action={loginUser} className="flex flex-col">
Burde vi bruke shadcn sin Form-komponent overalt? (Jeg brukte den på reservasjonssida)

2024-01-29 16:12 UTC, MindChirp commented
Vi trenger også form feedback dersom brukernavn og passord er feil.

2024-01-31 11:33 UTC, MindChirp approved these changes
Bra jobba! Prøv å ordne sånn at man kun har én form-feedback komponent på bunn, slik at man ikke får den samme feilmeldingen under begge feltene

![image](https://github.com/TIHLDE/kontresv2/assets/33499052/6660498a-2ebb-41e5-b478-52e9bea8a38d)

2024-02-01 16:57 UTC, MindChirp requested changes

2024-02-01 16:57 UTC, MindChirp commented on src/app/login/components/LoginForm.tsx
> +                        <Input placeholder="passord" {...field} />
Husk å sette type="password"! Glemte å nevne det her om dagen

2024-02-02 02:53 UTC, ConradOsvik commented on src/app/login/components/LoginForm.tsx
> +                        <Input placeholder="passord" {...field} />
ye tenkte på det men så kokte det bort etter jeg dro hjem, cleaner opp i morgen også pusher jeg en versjon med kun en form error message. må også ta en titt og se at mobile ikke ser helt krise ut

2024-02-02 16:26 UTC, ConradOsvik commented
La til en sjapp commit nå som fikser password input type + error message. Den så grei ut på mobil hvis vi får fikset headeren sin posisjon til fixed. orker ikke fikse det nå pga hodepine 🤕. kan hende jeg tar det senere i helgen

2024-02-02 16:41 UTC, MindChirp approved these changes

2024-02-02 16:41 UTC, MindChirp commented
Jeg har approva - bare å merge inn i main når du føler for det

2024-02-02 21:43 UTC, merged