Feat/fancy landing title
TIHLDE/kontresv2 pull request #48
Opened 2024-02-21 01:23 UTC by MindChirp

Implemented the following features:
- Made the landing page title more fancy by animating a custom css property, which by extension animates a background gradient.
- The text gradient animation plays automatically when entering the page.

![image](https://github.com/TIHLDE/kontresv2/assets/33499052/4c7da314-8773-4cfe-b3c9-1b9d78b487d3)

2024-02-22 00:00 UTC, ConradOsvik commented
Hva er denne zip-bomben 😵‍💫. Er det en videreføring av Embret sin zip-bomb?

2024-02-22 00:00 UTC, ConradOsvik commented
kul landing page doe 😎

2024-02-22 00:10 UTC, MindChirp commented
> Hva er denne zip-bomben 😵‍💫. Er det en videreføring av Embret sin zip-bomb?

Haha ja, jeg baserte denne branchen på branchen hans

2024-02-22 10:18 UTC, MindChirp commented
> Member

betyr det at du har godkjent PR-en? Kan du isåfall huke det av i github?

2024-02-22 11:09 UTC, ConradOsvik commented
> > kul landing page doe 😎
> 
> @ConradOsvik betyr det at du har godkjent PR-en? Kan du isåfall huke det av i github?

har ikke fått gått gjennom men gjør det senere i dag

2024-02-22 17:19 UTC, ConradOsvik requested changes
Veldig mye bra. vet ikke hvor mye av det som kanskje burde endres som har noe med landing pagen å gjøre, men burde kanskje fikses snarere enn senere. @MindChirp se over om du er enig så godkjenner jeg den etterpå. Veldig bra forside!

2024-02-22 17:19 UTC, ConradOsvik commented on src/app/[type]/page.tsx
> +    console.log('item', item);
skal denne logges?

2024-02-22 17:19 UTC, ConradOsvik commented on src/components/layout/.md
burde fjernes

2024-02-22 17:19 UTC, ConradOsvik commented on src/components/ui/calendar/existing-reservations.tsx
> +        console.log('res', reservation);
skal denne logges?

2024-02-22 17:19 UTC, ConradOsvik commented on src/components/ui/date-time-picker.tsx
> +    console.log(
to log or not to log?

2024-02-22 17:19 UTC, ConradOsvik commented on src/utils/.md
burde fjernes

2024-02-22 17:20 UTC, ConradOsvik commented
vet heller ikke hva som er rett på konflikten i theme-mode-toggler. kanskje du vet @MindChirp hvilken som burde stå

2024-02-22 17:21 UTC, MindChirp commented on src/app/[type]/page.tsx
> +    console.log('item', item);
Nope

2024-02-22 17:21 UTC, MindChirp commented on src/components/ui/calendar/existing-reservations.tsx
> +        console.log('res', reservation);
🤡

2024-02-22 17:22 UTC, MindChirp commented on src/components/ui/date-time-picker.tsx
> +    console.log(
Haha jeg mistenker at det er Embret sitt verk

2024-02-22 18:27 UTC, MindChirp commented
> vet heller ikke hva som er rett på konflikten i theme-mode-toggler. kanskje du vet @MindChirp hvilken som burde stå

Ja, det burde nok la seg ordne

2024-02-23 15:48 UTC, ConradOsvik approved these changes
Bra jobba! clean forside 😎

2024-02-23 15:48 UTC, merged